apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virtualization
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift-virtualization
    repoURL: https://github.com/adnan-drina/gitops-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: HyperConverged
      namespace: openshift-cnv
      jsonPointers:
        - /spec/version