---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: demo-storagecluster
  namespace: openshift-storage
spec:
  manageNodes: false
  monPVCTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp2
  storageDeviceSets:
    - count: 3
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Ti
          storageClassName: gp2
          volumeMode: Block
      name: deviceset
      placement: {}
      portable: true
      resources: {}