apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-codeready-workspaces
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift-codeready-workspaces
    repoURL: https://github.com/adnan-drina/gitops-sandbox.git
    targetRevision: HEAD
  syncPolicy:
    automated: { }
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: CheCluster
      namespace: codeready-workspaces
      jsonPointers:
        - /spec/auth/identityProviderURL