apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
  namespace: codeready-workspaces
spec:
  server:
    cheFlavor: codeready
    tlsSupport: true
    selfSignedCert: false
  database:
    externalDb: false
    chePostgresHostName: postgres
    chePostgresPort: '5432'
    chePostgresDb: dbche
  auth:
    openShiftoAuth: true
    externalIdentityProvider: false
#    identityProviderURL: ''
    identityProviderRealm: codeready
    identityProviderClientId: codeready-public
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
  metrics:
    enable: true
