apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-openshift-codeready-workspaces
  namespace: codeready-workspaces
rules:
  - apiGroups:
      - org.eclipse.che
    resources:
      - checlusters
    verbs:
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ogaac-openshift-codeready-workspaces
  namespace: codeready-workspaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-openshift-codeready-workspaces
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops